on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: Check installation

jobs:
  run-tests:
    runs-on: ${{ matrix.os }}-latest
    name: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macOS, Windows, Ubuntu]
    steps:
      - uses: royratcliffe/swi-prolog-actions@action-yml
      - name: Check installation
        run: swipl -t check_installation
      - uses: actions/checkout@v2
