on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: Run Tests

jobs:
  run-tests:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest}
          - {os: windows-latest}
          - {os: ubuntu-latest}
    steps:
      # Install SWI-Prolog
      #
      # Stable versions install on macOS and Windows whereas Linux installs the
      # development version. Gives wider version coverage.
      #
      # https://formulae.brew.sh/formula/swi-prolog
      # https://community.chocolatey.org/packages/SWI-Prolog
      # https://www.swi-prolog.org/build/PPA.html
      - name: Install SWI-Prolog
        run: |
          case $RUNNER_OS in
            macOS|Linux)
              brew install swi-prolog
              ;;
            Windows)
              choco install SWI-Prolog
              echo "C:\\Program Files\\swipl\\bin" >> $GITHUB_PATH
              ;;
            *)
              exit 1
          esac
        shell: bash
      - name: Check installation
        run: swipl -t check_installation
      - uses: actions/checkout@v2
