on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: Run Tests

jobs:
  run-tests:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest}
          - {os: windows-latest}
          - {os: ubuntu-latest}
    steps:
      # Install SWI-Prolog
      #
      # Stable versions install on macOS and Windows whereas Linux installs the
      # development version. Gives wider version coverage.
      #
      # https://formulae.brew.sh/formula/swi-prolog
      # https://community.chocolatey.org/packages/SWI-Prolog
      # https://www.swi-prolog.org/build/PPA.html
      - name: Install SWI-Prolog on macOS
        if: runner.os == 'macOS'
        run: brew install swi-prolog
      - name: Install SWI-Prolog on Windows
        if: runner.os == 'Windows'
        run: |
          choco install SWI-Prolog
          echo "C:\\Program Files\\swipl\\bin" >> $GITHUB_PATH
        shell: bash
      - name: Install SWI-Prolog on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-add-repository ppa:swi-prolog/devel
          sudo apt-get update
          sudo apt-get install swi-prolog
      - name: Check installation
        run: swipl -t check_installation
      - uses: actions/checkout@v2
