on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: Run Tests

jobs:
  run-tests:
    runs-on: ${{ matrix.os }}-latest
    name: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos, windows, ubuntu]
    steps:
      # https://formulae.brew.sh/formula/swi-prolog
      # https://community.chocolatey.org/packages/SWI-Prolog
      - name: Install SWI-Prolog
        run: |
          case $RUNNER_OS in
            macOS|Linux)
              brew install swi-prolog
              ;;
            Windows)
              choco install SWI-Prolog
              echo "C:\\Program Files\\swipl\\bin" >> $GITHUB_PATH
              ;;
            *)
              exit 1
          esac
        shell: bash
      - name: Check installation
        run: swipl -t check_installation
      - uses: actions/checkout@v2
